version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true

    environment:
      FLUTTER_VERSION: 1.4.7

    steps:
      - checkout
      - run: ./build_docker.sh
      - run: ./push_docker.sh
